/**
 * Normalize a given URL by trimming whitespace, prepending with "https://" if necessary, converting to lowercase, and removing a trailing slash if present.
 * @param {string} url The URL to normalize.
 * @returns {string} The normalized URL.
 */
export function normalizeUrl(url: string): string {
  let normalized = url.trim();

  if (!normalized.match(/^https?:\/\//i)) {
    normalized = `https://${normalized}`;
  }

  normalized = normalized.toLowerCase();

  if (normalized.endsWith("/")) {
    normalized = normalized.slice(0, -1);
  }

  return normalized;
}

/**
 * Validate whether a given URL is valid or not.
 * @param {string} url The URL to validate.
 * @returns {boolean} true if the URL is valid, false otherwise.
 */
export function validateUrl(url: string): boolean {
  try {
    const urlObj = new URL(url.match(/^https?:\/\//i) ? url : `https://${url}`);
    return urlObj.protocol === "http:" || urlObj.protocol === "https:";
  } catch {
    return false;
  }
}

/**
 * Returns the domain name of a given URL.
 * If the URL is invalid, an empty string is returned.
 * @param {string} url The URL to get the domain name from.
 * @returns {string} The domain name of the given URL.
 */
export function getDomain(url: string): string {
  try {
    const urlObj = new URL(url.match(/^https?:\/\//i) ? url : `https://${url}`);
    return urlObj.hostname;
  } catch {
    return "";
  }
}

/**
 * Returns a cache key for the given URL.
 * The cache key is generated by prepending "digger_cache_" to the normalized URL.
 * @param {string} url The URL to generate a cache key for.
 * @returns {string} The cache key for the given URL.
 */
export function getCacheKey(url: string): string {
  const normalized = normalizeUrl(url);
  return `digger_cache_${normalized}`;
}
